shopware_vagrant = File.expand_path('./vendor/best-it/shopware-vagrant/Vagrantfile')
load shopware_vagrant

confDir = $confDir ||= File.expand_path(File.dirname(__FILE__))
afterScriptPath = confDir + "/after.sh"
customizationScriptPath = confDir + "/user-customizations.sh"

Vagrant.configure("2") do |config|

    config.vm.synced_folder "./shopware", "/home/vagrant/www",
        type: "rsync",
        rsync__exclude: [
            "/.env",
            "/engine/Library",
            "/var/*",
            "/web/*",
            "/media/.htaccess",
            "/.htaccess",
            "/themes/Backend",
            "/themes/Frontend/Bare",
            "/themes/Frontend/Responsive"
        ]

    config.ssh.forward_agent = true

    if File.exist? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath, privileged: false, keep_color: true
    end

    if File.exist? customizationScriptPath then
        config.vm.provision "shell", path: customizationScriptPath, privileged: false, keep_color: true
    end
end

userVagrantfilePath = confDir + "/user-vagrantfile"
load userVagrantfilePath if File.exists?(userVagrantfilePath)
