---
- name: download composer
  get_url:
    url: https://getcomposer.org/download/{{ composer_version }}/composer.phar
    dest: /tmp/composer.phar
  tags: composer

- name: rename and mv composer.phar to composer
  shell: mv -f /tmp/composer.phar /home/vagrant/bin/composer
  args:
    creates: /home/vagrant/bin/composer
  tags: composer

- name: make composer executable
  file:
    path: /home/vagrant/bin/composer
    mode: a+x
    state: file
  tags: composer
